import 'package:get/get.dart';
import 'dart:ui';

/// 切换语言
class LanguageChangeController extends GetxController {

  void changeLanguage(String languageCode, String  countryCode) {
    var locale = Locale(languageCode, countryCode);
    Get.updateLocale(locale);
  }
}

class Language extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'zh': {
      // 系统
      '我的': '我的',
      '号码': '號碼',
      '临时邮箱': '臨時郵箱',
      '国家': '國家',

      // 登陆
      '登陆': '登陸',
      '登陆到您的账户': '登陸到您的\n賬戶',
      '登陆失败': '登陸失敗',
      '电子邮箱': '電子郵箱',
      '用户名必须为电子邮箱': '用戶名必須為電子郵箱',
      '邮箱地址不能为空': '郵箱地址不能為空',
      '密码': '密碼',
      '不能少于6位字符': '不能少於6位字符',
      '记住密码': '記住密碼',
      '忘记密码': '忘記密碼',
      '电子邮箱登陆': '電子郵箱登陸',
      'Google登陆': 'Google登陸',
      '没有账号': '沒有賬號? ',
      'Google登陆失败,请检查网络是否连接': 'Google登陸失敗,請檢查網絡是否連接',
      '找回密码': '找回密碼',
      '将发送更改密码邮件到': '將發送更改密碼郵件到 ',
      '更改密码邮件发送成功': '更改密碼郵件發送成功',
      '将发送验证邮件到': '將發送驗證郵件到 ',
      '验证邮件发送成功': '驗證郵件發送成功',
      '邮件已经发送,如果没有,请查看垃圾邮箱,请勿频繁发送': '郵件已經發送,如果沒有,請查看垃圾郵箱,請勿頻繁發送',

      // 注册
      '注册': '註冊',
      '注册新账号': '註冊新\n賬號',
      '注册账号': '註冊賬號',
      '注册成功': '註冊成功',
      '登陆成功': '登陸成功',
      '重复密码': '重複密碼',
      '两次密码必须相同': '兩次密碼必須相同',
      '创建账号即表示同意我们的': '創建賬號即表示同意我們的',
      '隐私条款': '隱私條款',
      '已经有一个账号': '已經有一個賬號? ',
      '请选择同意': '請選擇同意',
      '验证码': '驗證碼',
      '用户名不能为空': '用戶名不能為空',
      '发送验证码': '發送驗證碼',
      '秒后重新获取': '秒後重新獲取',

      // 号码
      '随机号码': '隨機號碼',
      '收藏': '收藏號碼',
      '无法接收': '無法接收?',
      '关于无法接收': '關於無法接收',
      '为什么接收不到': '如果多次刷新都無法接收，那就有可能是该号码使用人數過多，验证码发送频繁，導致您要註冊的app或網站並沒有真正地發送驗證碼，並不是我們沒有接收到，解決辦法就是等一段时间后再尝试刷新，或者更換號碼重新接收 \n\n點擊OK向我們反饋該號碼接收異常',
      '下拉页面刷新以获取新消息': '下拉頁面刷新以獲取新消息.',
      '新消息将在大约30秒后到达': '新消息將在大約30秒後到達,請勿頻繁刷新.',
      '任何人都可以看到这个号码的消息': '任何人都可以看到這個號碼的消息,請不要用來綁定重要賬戶.',
      '预告号码': '預告號碼',
      '上线时间': '上線時間',
      '反馈成功': '反饋成功',
      '反馈失败': '反饋失敗',
      '号码上线倒计时': '號碼上線倒計時',
      '金币数量': '金幣數量',
      '使用号码': '使用號碼',
      '观看广告获得奖励': '觀看廣告,獲得獎勵',
      '仅需支付一次,成功后下次可直接使用': '提醒：僅需支付一次,成功後下次可直接使用',
      '预告': '預告',

      // 匿名邮箱
      '请选择邮箱后坠': '請選擇郵箱後墜',
      '复制': '複製',
      '创建': '創建',
      '刷新': '刷新',
      '删除': '刪除',
      '请先申请邮箱地址': '請先申請郵箱地址',
      '复制成功': '複製成功',
      '邮箱创建成功': '郵箱創建成功',
      '正在使用中,如需更换,请先销毁': '正在使用中,如需更換,請先銷毀',
      '邮箱地址不存在,请先创建': '郵箱地址不存在,請先創建',
      '确定删除': '確定刪除?',
      '删除成功': '刪除成功',
      '删除后,将永远无法找回': '刪除後,將永遠無法找回!!!',
      '随机注册邮箱': '隨機註冊郵箱',
      '指定用户名注册': '指定用戶名註冊',
      '暂未收到新邮件': '暫未收到新郵件',
      '收到新邮件': '收到新郵件',
      '邮件内容': '郵件內容',
      '自动获取': '自動獲取',

      // 我的
      '登陆会员后解锁更多功能': '登陸會員後解鎖更多功能',
      '欢迎回来': '歡迎回來！',
      '个人中心': '個人中心',
      'VIP号码': 'VIP號碼',
      '会员专属号码': '會員專屬號碼',
      '收藏号码': '收藏號碼',
      '查询所有收藏号码': '查詢所有收藏號碼',
      '设置语言': '設置語言',
      '夜晚模式': '夜晚模式',
      '夜晚': '夜晚',
      '清理缓存': '清理緩存',
      '缓存清理成功': '緩存清理成功，请重新啟動APP！！！',
      '系统无法正常使用时,尝试此功能': '系統無法正常使用時,嘗試此功能',
      '缓存清理后,需要重新启动APP': '緩存清理後,需要重新啟動APP',
      '版本': '版本',
      '确定退出': '確定退出?',
      '退出后,将无法享受更多高级功能': '退出後,將無法享受更多高級功能',
      '退出': '退出',
      '账号退出成功': '賬號退出成功',
      '永久免费': '永久免費',
      '邮箱验证': '郵箱驗證',

      // 购买
      '金币': '金幣',
      '当前金币不足观看广告获取更多金币': '當前金幣不足,觀看廣告獲取更多金幣',

      // 其他通用
      '通知': '通知',
      '错误': '錯誤',
      '尝试下拉刷新': '嘗試下拉刷新',
      '列表为空': '列表為空',
      '全部加载完成': '全部加載完成',
      '请求失败': '請求失敗',
      '不再显示': '不再顯示',
      '已阅': '已閱',
      '无法连接到Google,部分功能将无法使用': '無法連接到Google,部分功能將無法使用',
      '加载中': '加载中',
      '跳过': '跳過',
      '再按一次退出app': '再按一次退出app',
      '系统初始化': '系統初始化...',
      '系统初始化成功': '系統初始化成功...',
      '系统加载配置': '系統加載配置...',
      '正在进入系统': '正在進入系統...',
      '请关闭广告插件': '為了更好的服務到您，請您關閉屏蔽廣告插件，感謝您的支持！ ！ ！',
      '出现异常请重新启动APP': '出現異常,請重新啟動APP!!!',
      '是否与本地账号进行合并': '是否與本地賬號進行合併',
      '账户合并失败': '賬戶合併失敗,如需合併,請聯繫客服處理',
      '本地账户登陆异常': '本地賬戶登陸異常,合併失敗',

    },
    'en': {
      // 系统
      '我的': 'My',
      '号码': ' Number',
      '临时邮箱': 'Temp email',
      '国家': 'Country',

      // 登陆
      '登陆': 'Login',
      '登陆到您的账户': 'Login to your\nAccount',
      '登陆失败': 'Login failed',
      '电子邮箱': 'E-mail',
      '用户名必须为电子邮箱': 'Username must be email',
      '邮箱地址不能为空': 'Email address cannot be empty',
      '密码': 'Password',
      '不能少于6位字符': 'Cannot be less than 6 characters',
      '记住密码': 'Remember',
      '忘记密码': 'Forgot password',
      '电子邮箱登陆': 'Email login',
      'Google登陆': 'Google login',
      '没有账号': 'No account? ',
      'Google登陆失败,请检查网络是否连接': 'Google login failed, please check the network connection',
      '找回密码': 'Retrieve password',
      '将发送更改密码邮件到': 'A password change email will be sent to ',
      '更改密码邮件发送成功': 'Password change email sent successfully',
      '将发送验证邮件到': 'A verification email will be sent to ',
      '验证邮件发送成功': 'Verify email sent successfully',
      '邮件已经发送,如果没有,请查看垃圾邮箱,请勿频繁发送': 'The email has been sent, if not, please check the spam mailbox, please do not send frequently',

      // 注册
      '注册': 'Register',
      '注册新账号': 'Register new \n Account',
      '注册账号': 'Register an account',
      '注册成功': 'Registration success',
      '登陆成功': 'Log in success',
      '重复密码': 'Repeat password',
      '两次密码必须相同': 'Both passwords must be the same',
      '创建账号即表示同意我们的': 'By creating an account, you agree to our',
      '隐私条款': 'Privacy Policy',
      '已经有一个账号': 'Already have an account? ',
      '请选择同意': 'Please choose to agree',
      '验证码': 'Verification code',
      '用户名不能为空': 'Username can not be empty',
      '发送验证码': 'Send code',
      '秒后重新获取': ' Reacquire',

      // 号码
      '随机号码': 'Random',
      '收藏': 'Favorites',
      '无法接收': 'Unavailable?',
      '关于无法接收': 'About unavailable to receive sms',
      '为什么接收不到': 'If the number cannot be received after multiple refreshes, it is possible that the number is used by too many people and the verification code is sent frequently, so that the app or website you want to register does not really send the verification code. It is not that we did not receive it. The solution is to Wait for a while and then try to refresh, or change the number to receive again \n\nClick OK to report to us that the number is not receiving correctly',
      '下拉页面刷新以获取新消息': 'Pull down the page to refresh to get new message.',
      '新消息将在大约30秒后到达': 'New message will arrive in about 30 seconds.',
      '任何人都可以看到这个号码的消息': 'Anyone can see the message of this number.',
      '预告号码': 'Upcoming new number',
      '上线时间': 'Online time',
      '反馈成功': 'Feedback success',
      '反馈失败': 'Feedback failed',
      '号码上线倒计时': 'Number online countdown',
      '金币数量': 'Number of coins',
      '使用号码': 'Use number',
      '观看广告获得奖励': 'Watch ads and get rewarded',
      '仅需支付一次,成功后下次可直接使用': 'Hint: Pay only once, use it directly next time',
      '预告': 'Upcoming',

      // 匿名邮箱
      '请选择邮箱后坠': 'Please select Email Site',
      '复制': 'Copy',
      '创建': 'Create',
      '刷新': 'Refresh',
      '删除': 'Delete',
      '请先申请邮箱地址': 'Please request an email address first',
      '复制成功': 'Copy successfully',
      '邮箱创建成功': 'Email created successfully',
      '正在使用中,如需更换,请先销毁': 'In use, if you need to replace it, please destroy it first',
      '邮箱地址不存在,请先创建': 'Email address does not exist, please create it first',
      '确定删除': 'Confirm delete?',
      '删除成功': 'Delete successful',
      '删除后,将永远无法找回': 'Once deleted, it will never be retrieved!!!',
      '随机注册邮箱': 'Random registered email',
      '指定用户名注册': 'Specify username to register',
      '暂未收到新邮件': 'No new emails received yet',
      '收到新邮件': 'Received new mail',
      '邮件内容': 'Email content',
      '自动获取': 'Auto request',

      // 我的
      '登陆会员后解锁更多功能': 'Unlock more functions after logging in as a member',
      '欢迎回来': 'Welcome back！',
      '个人中心': 'Personal Center',
      'VIP号码': 'VIP number',
      '会员专属号码': 'Member exclusive number',
      '收藏号码': 'Favorite number',
      'vip号码': 'VIP number',
      '查询所有收藏号码': 'Query all favorite numbers',
      '设置语言': 'Language setting',
      '夜晚模式': 'Dark',
      '夜晚': 'Dark',
      '清理缓存': 'Clear cache',
      '缓存清理成功': 'Cache clear successfully, Please restart the APP!!!',
      '系统无法正常使用时,尝试此功能': 'Try this function when the system cannot be used normally',
      '缓存清理后,需要重新启动APP': 'After clearing the cache, you need to restart the app',
      '版本': 'Version',
      '确定退出': 'Are you sure to exit?',
      '退出后,将无法享受更多高级功能': 'After exiting, you will not be able to enjoy more advanced features',
      '退出': 'Quit',
      '账号退出成功': 'Account logout successfully',
      '永久免费': 'Permanently free',
      '邮箱验证': 'Email verification',

      // 购买
      '金币': 'Coins',
      '当前金币不足观看广告获取更多金币': 'Currently there is not enough Coins, watch ads to get more points',
      '广告观看完成': 'The ads is watched, the reward is issued, and the number of coins in the account:',

      // 其他通用
      '通知': 'Notice',
      '错误': 'Error',
      '尝试下拉刷新': 'Try the drop-down refresh',
      '列表为空': 'The list is empty',
      '全部加载完成': 'All loading completed',
      '请求失败': 'Request failed',
      '不再显示': 'Don\'t show again',
      '已阅': 'Read',
      '无法连接到Google,部分功能将无法使用': 'Unable to connect to Google, some functions will not be available',
      '加载中': 'Loading',
      '跳过': 'Skip',
      '再按一次退出app': 'Press again to exit app',
      '系统初始化': 'System initialize...',
      '系统初始化成功': 'System initialized successfully...',
      '系统加载配置': 'System loading configuration...',
      '正在进入系统': 'Entering system...',
      '请关闭广告插件': 'In order to serve you better, please close the Adblock plugin, thank you for your support! ! !',
      '出现异常请重新启动APP': 'There is an exception, please restart the APP !!!',
      '是否与本地账号进行合并': 'Whether to merge with local accounts',
      '账户合并失败': 'Account merger failed, if you need to merge, please contact customer service for processing',
      '本地账户登陆异常': 'The login of the local account is abnormal and the merge fails.',

    },
    'pt': {
      // 系统
      '我的': 'minha',
      '号码': 'Número',
      '临时邮箱': 'caixa de correio temporária',
      '国家': 'nação',

      // 登陆
      '登陆': 'Conecte-se',
      '登陆到您的账户': 'Faça login na sua conta',
      '登陆失败': 'falhou ao fazer login',
      '电子邮箱': 'E-mail',
      '用户名必须为电子邮箱': 'O nome de usuário deve ser e-mail',
      '邮箱地址不能为空': 'O endereço de e-mail não pode estar vazio',
      '密码': 'senha',
      '不能少于6位字符': 'Não pode ter menos de 6 caracteres',
      '记住密码': 'lembrar senha',
      '忘记密码': 'Esqueceu a senha',
      '电子邮箱登陆': 'E-mail de login',
      'Google登陆': 'Login do Google',
      '没有账号': 'Sem conta? ',
      'Google登陆失败,请检查网络是否连接': 'Falha no login do Google. Verifique se a rede está conectada',
      '找回密码': 'Recuperar Senha',
      '将发送更改密码邮件到': 'enviará um e-mail de alteração de senha para ',
      '更改密码邮件发送成功': 'Email de alteração de senha enviado com sucesso',
      '将发送验证邮件到': 'Um e-mail de verificação será enviado para ',
      '验证邮件发送成功': 'Verifique se o e-mail foi enviado com sucesso',
      '邮件已经发送,如果没有,请查看垃圾邮箱,请勿频繁发送': 'O e-mail foi enviado, caso contrário, verifique a caixa de spam, não envie com frequência',

      // 注册
      '注册': 'registro',
      '注册新账号': 'Registrar uma nova conta',
      '注册账号': 'Registre uma conta',
      '注册成功': 'Sucesso no registro',
      '登陆成功': 'Aterrissou com sucesso',
      '重复密码': 'Repita a senha',
      '两次密码必须相同': 'Ambas as senhas devem ser iguais',
      '创建账号即表示同意我们的': 'Ao criar uma conta, você concorda com nossos',
      '隐私条款': 'Política de Privacidade',
      '已经有一个账号': 'já tem uma conta? ',
      '请选择同意': 'Por favor, escolha concordar',
      '验证码': 'Código de verificação',
      '用户名不能为空': 'O nome de usuário não pode estar vazio',
      '发送验证码': 'Envie o código de verificação',
      '秒后重新获取': 'Recarregue em segundos',

      // 号码
      '随机号码': 'aleatório',
      '收藏': 'coletar',
      '无法接收': 'Indisponível?',
      '关于无法接收': 'Sobre não poder receber',
      '为什么接收不到': 'Se o número não puder ser recebido após várias atualizações, pode ser que o número seja usado por muitas pessoas e o código de verificação seja enviado com frequência, de modo que o aplicativo ou site que você deseja registrar não envie realmente o código de verificação. não que não tenhamos recebido. A solução é aguardar um pouco e tentar atualizar ou alterar o número para receber novamente \n\nClique em OK para nos informar que o número foi recebido de forma anormal',
      '下拉页面刷新以获取新消息': 'Puxe a página para baixo para atualizar para novas mensagens.',
      '新消息将在大约30秒后到达': 'Novas mensagens chegarão em cerca de 30 segundos.',
      '任何人都可以看到这个号码的消息': 'Qualquer pessoa pode ver as mensagens deste número.',
      '预告号码': 'Número antecipado',
      '上线时间': 'tempo online',
      '反馈成功': 'sucesso do feedback',
      '反馈失败': 'feedback falhou',
      '号码上线倒计时': 'Número de contagem regressiva on-line',
      '金币数量': 'Número de moedas de ouro',
      '使用号码': 'usar número',
      '观看广告获得奖励': 'Assista a anúncios e seja recompensado',
      '仅需支付一次,成功后下次可直接使用': 'Lembrete: você só precisa pagar uma vez e pode usá-lo diretamente na próxima vez após o sucesso',
      '预告': 'perceber',

      // 匿名邮箱
      '请选择邮箱后坠': 'Por favor, selecione a caixa de correio',
      '复制': 'cópia de',
      '创建': 'crio',
      '刷新': 'atualizar',
      '删除': 'excluir',
      '请先申请邮箱地址': 'Por favor, solicite um endereço de e-mail primeiro',
      '复制成功': 'Copiar com sucesso',
      '邮箱创建成功': 'E-mail criado com sucesso',
      '正在使用中,如需更换,请先销毁': 'Em uso, se você precisar substituí-lo, destrua-o primeiro',
      '邮箱地址不存在,请先创建': 'O endereço de e-mail não existe, crie-o primeiro',
      '确定删除': 'confirmar excluir?',
      '删除成功': 'excluído com sucesso',
      '删除后,将永远无法找回': 'Uma vez excluído, ele nunca será recuperado!!!',
      '随机注册邮箱': 'E-mail cadastrado aleatório',
      '指定用户名注册': 'Registre-se com um nome de usuário especificado',
      '暂未收到新邮件': 'Nenhum novo e-mail recebido ainda',
      '收到新邮件': 'novo e-mail recebido',
      '邮件内容': 'conteúdo do e-mail',
      '自动获取': 'automática',

      // 我的
      '登陆会员后解锁更多功能': 'Desbloqueie mais funções depois de fazer login como membro',
      '欢迎回来': 'Bem vindo de volta！',
      '个人中心': 'centro pessoal',
      'VIP号码': 'número VIP',
      '会员专属号码': 'Número exclusivo do membro',
      '收藏号码': 'Número favorito',
      '查询所有收藏号码': 'Consultar todos os números favoritos',
      '设置语言': 'configuração de idioma',
      '夜晚模式': 'modo noturno',
      '夜晚': 'noite',
      '清理缓存': 'Limpar cache',
      '缓存清理成功': 'O cache foi limpo com sucesso, reinicie o APP！！！',
      '系统无法正常使用时,尝试此功能': 'Quando o sistema não puder ser usado normalmente, tente esta função',
      '缓存清理后,需要重新启动APP': 'Depois que o cache é limpo, o aplicativo precisa ser reiniciado',
      '版本': 'Versão',
      '确定退出': 'OK para sair?',
      '退出后,将无法享受更多高级功能': 'Depois de sair, você não poderá desfrutar de recursos mais avançados',
      '退出': 'Sair',
      '账号退出成功': 'Logout da conta com sucesso',
      '永久免费': 'Livre para sempre',
      '邮箱验证': 'Verificação de e-mail',

      // 购买
      '金币': 'Coins',
      '当前金币不足观看广告获取更多金币': 'As moedas de ouro atuais não são suficientes para assistir a anúncios para obter mais moedas de ouro',

      // 其他通用
      '通知': 'Perceber',
      '错误': 'erro',
      '尝试下拉刷新': 'tente puxar para baixo para atualizar',
      '列表为空': 'lista está vazia',
      '全部加载完成': 'tudo carregado',
      '请求失败': 'Falha na solicitação',
      '不再显示': 'não mostre novamente',
      '已阅': 'ler',
      '无法连接到Google,部分功能将无法使用': 'Não foi possível se conectar ao Google, alguns recursos não funcionarão',
      '加载中': 'Carregando',
      '跳过': 'pular sobre',
      '再按一次退出app': 'Pressione novamente para sair do aplicativo',
      '系统初始化': 'inicialização do sistema...',
      '系统初始化成功': 'Inicialização do sistema bem-sucedida...',
      '系统加载配置': 'configuração de carga do sistema...',
      '正在进入系统': 'entrando no sistema...',
      '请关闭广告插件': 'Para melhor atendê-lo, feche o plug-in de bloqueio de anúncios, obrigado por seu apoio！ ！ ！',
      '出现异常请重新启动APP': 'Se ocorrer uma exceção, reinicie o APP!!!',
      '是否与本地账号进行合并': 'Se deve ser mesclado com a conta local',
      '账户合并失败': 'A fusão da conta falhou, se você precisar mesclar, entre em contato com o atendimento ao cliente',
      '本地账户登陆异常': 'O login da conta local está anormal e a fusão falha',

    },
    'de': {
      // 系统
      '我的': 'Mein',
      '号码': ' Nummer',
      '临时邮箱': 'Temporäre E-Mail',
      '国家': 'Land',

      // 登陆
      '登陆': 'Anmeldung',
      '登陆到您的账户': 'Melde dich in deinem \nKonto an',
      '登陆失败': 'Login fehlgeschlagen',
      '电子邮箱': 'E-mail',
      '用户名必须为电子邮箱': 'Benutzername muss E-Mail sein',
      '邮箱地址不能为空': 'Die E-Mail-Adresse darf nicht leer sein',
      '密码': 'Passwort',
      '不能少于6位字符': 'Darf nicht weniger als 6 Zeichen lang sein',
      '记住密码': 'Denken Sie daran',
      '忘记密码': 'Passwort vergessen',
      '电子邮箱登陆': 'E-Mail-Anmeldung',
      'Google登陆': 'Google-Anmeldung',
      '没有账号': 'Kein Account? ',
      'Google登陆失败,请检查网络是否连接': 'Google-Anmeldung fehlgeschlagen, bitte überprüfen Sie die Netzwerkverbindung',
      '找回密码': 'Passwort abrufen',
      '将发送更改密码邮件到': 'Eine Passwortänderungs-E-Mail wird an gesendet ',
      '更改密码邮件发送成功': 'E-Mail zur Passwortänderung erfolgreich gesendet',
      '将发送验证邮件到': 'Eine Bestätigungs-E-Mail wird an gesendet ',
      '验证邮件发送成功': 'Bestätigen Sie, dass die E-Mail erfolgreich gesendet wurde',
      '邮件已经发送,如果没有,请查看垃圾邮箱,请勿频繁发送': 'Die E-Mail wurde gesendet, wenn nicht, überprüfen Sie bitte das Spam-Postfach, senden Sie sie bitte nicht häufig',

      // 注册
      '注册': 'Registrieren',
      '注册新账号': 'Neuen Account Registrieren',
      '注册账号': 'Einen Account registrieren',
      '注册成功': 'Registrierung erfolgreich',
      '登陆成功': 'Einloggen erfolgreich',
      '重复密码': 'Passwort wiederholen',
      '两次密码必须相同': 'Beide Passwörter müssen gleich sein',
      '创建账号即表示同意我们的': 'Indem Sie ein Konto erstellen, stimmen Sie unseren zu',
      '隐私条款': 'Datenschutz-Bestimmungen',
      '已经有一个账号': 'Sie haben bereits ein Konto? ',
      '请选择同意': 'Bitte stimmen Sie zu',
      '验证码': 'Verifizierungs-Schlüssel',
      '用户名不能为空': 'Der Benutzername darf nicht leer sein',
      '发送验证码': 'Code senden',
      '秒后重新获取': ' Erlangen',

      // 号码
      '随机号码': 'Zufällig',
      '收藏': 'sammeln',
      '无法接收': 'Scheitern?',
      '关于无法接收': 'Über die Unfähigkeit, SMS zu empfangen',
      '为什么接收不到': 'Wenn die Nummer nach mehreren Aktualisierungen nicht empfangen werden kann, kann es sein, dass die Nummer von zu vielen Personen verwendet wird und der Bestätigungscode häufig gesendet wird, sodass die App oder Website, die Sie registrieren möchten, den Bestätigungscode nicht wirklich sendet nicht, dass wir es nicht erhalten haben. Die Lösung besteht darin, eine Weile zu warten und dann zu versuchen, die Nummer zu aktualisieren oder zu ändern, um sie erneut zu erhalten \n\nKlicken Sie auf OK, um uns zu melden, dass die Nummer nicht normal empfangen wurde',
      '下拉页面刷新以获取新消息': 'Ziehen Sie die Seite nach unten, um sie zu aktualisieren und neue Nachrichten zu erhalten.',
      '新消息将在大约30秒后到达': 'Eine neue Nachricht wird in etwa 30 Sekunden eintreffen.',
      '任何人都可以看到这个号码的消息': 'Jeder kann die Nachricht dieser Nummer sehen.',
      '预告号码': 'Kommende neue Nummer',
      '上线时间': 'Online-Zeit',
      '反馈成功': 'Feedback-Erfolg',
      '反馈失败': 'Rückmeldung fehlgeschlagen',
      '号码上线倒计时': 'Zahlen-Online-Countdown',
      '金币数量': 'Anzahl Münzen',
      '使用号码': 'Nummer verwenden',
      '观看广告获得奖励': 'Werbung ansehen und belohnt werden',
      '仅需支付一次,成功后下次可直接使用': 'Tipp: Nur einmal bezahlen, beim nächsten Mal direkt nutzen',
      '预告': 'Bevorstehende',

      // 匿名邮箱
      '请选择邮箱后坠': 'Bitte wählen Sie E-Mail-Site',
      '复制': 'Kopieren',
      '创建': 'Schaffen',
      '刷新': 'Aktualisierung',
      '删除': 'Löschen',
      '请先申请邮箱地址': 'Bitte fordern Sie zuerst eine E-Mail-Adresse an',
      '复制成功': 'Erfolgreich kopieren',
      '邮箱创建成功': 'E-Mail erfolgreich erstellt',
      '正在使用中,如需更换,请先销毁': 'Wenn Sie es im Gebrauch ersetzen müssen, zerstören Sie es bitte zuerst',
      '邮箱地址不存在,请先创建': 'E-Mail-Adresse existiert nicht, bitte erstellen Sie sie zuerst',
      '确定删除': 'Löschen bestätigen?',
      '删除成功': 'Löschen erfolgreich',
      '删除后,将永远无法找回': 'Einmal gelöscht, wird es nie wiederhergestellt!!!',
      '随机注册邮箱': 'Zufällige registrierte E-Mail',
      '指定用户名注册': 'Geben Sie den zu registrierenden Benutzernamen an',
      '暂未收到新邮件': 'Noch keine neuen E-Mails erhalten',
      '收到新邮件': 'Neue Post erhalten',
      '邮件内容': 'E-Mail-Inhalt',
      '自动获取': 'Auto-Anfrage',

      // 我的
      '登陆会员后解锁更多功能': 'Schalte weitere Funktionen frei, nachdem du dich als Mitglied angemeldet hast',
      '欢迎回来': 'Willkommen zurück!',
      '个人中心': 'Persönliches Zentrum',
      'VIP号码': 'VIP-Nummer',
      '会员专属号码': 'Exklusive Mitgliedsnummer',
      '收藏号码': 'Lieblingsnummer',
      'vip号码': 'VIP-Nummer',
      '查询所有收藏号码': 'Alle Lieblingsnummern abfragen',
      '设置语言': 'Spracheinstellungen',
      '夜晚模式': 'Dunkel',
      '夜晚': 'Dunkel',
      '清理缓存': 'Cache leeren',
      '缓存清理成功': 'Cache erfolgreich gelöscht, Bitte starten Sie die APP neu!!!',
      '系统无法正常使用时,尝试此功能': 'Probieren Sie diese Funktion aus, wenn das System nicht normal verwendet werden kann',
      '缓存清理后,需要重新启动APP': 'Nachdem Sie den Cache geleert haben, müssen Sie die App neu starten',
      '版本': 'Ausführung',
      '确定退出': 'Bist du sicher, dass du aufhören willst?',
      '退出后,将无法享受更多高级功能': 'Nach dem Beenden können Sie keine erweiterten Funktionen nutzen',
      '退出': 'Aufhören',
      '账号退出成功': 'Kontoabmeldung erfolgreich',
      '永久免费': 'Dauerhaft kostenlos',
      '邮箱验证': 'E-Mail-Verifizierung',

      // 购买
      '金币': 'Münzen',
      '当前金币不足观看广告获取更多金币': 'Derzeit sind nicht genügend Münzen vorhanden. Sehen Sie sich Anzeigen an, um mehr Punkte zu erhalten',
      '广告观看完成': 'Die Anzeigen werden angesehen, die Belohnung wird ausgegeben und die Anzahl der Münzen auf dem Konto:',

      // 其他通用
      '通知': 'Notiz',
      '错误': 'Fehler',
      '尝试下拉刷新': 'Probieren Sie die Dropdown-Aktualisierung aus',
      '列表为空': 'Die Liste ist leer',
      '全部加载完成': 'Alle Ladevorgänge abgeschlossen',
      '请求失败': 'Anfrage fehlgeschlagen',
      '不再显示': 'Nicht mehr anzeigen',
      '已阅': 'Lesen',
      '无法连接到Google,部分功能将无法使用': 'Es kann keine Verbindung zu Google hergestellt werden, einige Funktionen sind nicht verfügbar',
      '加载中': 'Wird geladen',
      '跳过': 'Überspringen',
      '再按一次退出app': 'Drücken Sie erneut, um die App zu beenden',
      '系统初始化': 'System initialisieren...',
      '系统初始化成功': 'System erfolgreich initialisiert...',
      '系统加载配置': 'Systemladekonfiguration...',
      '正在进入系统': 'Eingabesystem...',
      '请关闭广告插件': 'Um Ihnen einen besseren Service bieten zu können, schließen Sie bitte das Werbeblocker-Plug-in. Vielen Dank für Ihre Unterstützung! ! !',
      '出现异常请重新启动APP': 'Es gibt eine Ausnahme, bitte starten Sie die APP neu !!!',
      '是否与本地账号进行合并': 'Ob eine Zusammenführung mit dem lokalen Konto erfolgen soll',
      '账户合并失败': 'Die Kontozusammenführung ist fehlgeschlagen. Wenn Sie eine Zusammenführung benötigen, wenden Sie sich bitte an den Kundendienst',
      '本地账户登陆异常': 'Die Anmeldung des lokalen Kontos ist fehlerhaft und die Zusammenführung schlägt fehl',

    }


  };
}


